server:
  port: 8080
logging:
  level:
    org.jooq.tools.LoggerListener: OFF
    # 打开我们自定义的精简日志
    jooq.sql: INFO

cors:
  allowedOrigins: ${ALLOWED_ORIGINS}
  allowedMethods: ${ALLOWED_METHODS}
  allowedHeaders: ${ALLOWED_HEADERS}
  allowedExposeHeaders: ${ALLOWED_EXPOSE_HEADERS}
spring:
  application:
    name: workmate
  config:
    import: optional:file:.env[.properties]   # ?????? .env
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jooq:
    sql-dialect: MYSQL

  mail:
    host: ${MAIL_HOST:smtp.qq.com}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    port: ${MAIL_PORT:465}
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          # Some SMTPs require a sensible EHLO hostname; override via MAIL_LOCALHOST if needed
          localhost: ${MAIL_LOCALHOST:localhost}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: ${JWT_SECRET:dev-secret}
    ttlSeconds: 2592000
